apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "polygon-edge-k8s.fullname" . }}
  labels:
    {{- include "polygon-edge-k8s.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"