apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-dir-pvc
  labels:
    {{- include "polygon-edge-k8s.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi